version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - bridge
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=base
      - DB_USERNAME=root
      - DB_PASSWORD=0Paulo123#

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bridge
    environment:
      - MYSQL_ROOT_PASSWORD=0Paulo123#
      - MYSQL_DATABASE=base
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0Paulo123#

  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 9080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - bridge

networks:
  bridge:

volumes:
  db_data:
